### ISSUE TITLE
4. faza

### ISSUE THREAD

**Issue by SanjaAudi** [SanjaAudi/APPR-2014-15#5]
Prosim preglejte in povejte kaj je še treba storiti oziroma kaj ni v redu, da zaključim projekt. Najlepša hvala

**Comment by jaanos** [comment]
V glavnem programu odkomentiraj klic programa `analiza.r`, da se bo program izvedel v celoti. Ppravzaprav moraš poklicati program `analiza.r` v vrhnji mapi projekta, tako da bodisi odstrani mapo `analiza/` iz poti, ali pa program `analiza.r` premakni tja (tam že obstaja datoteka z istim imenom, ki pa je še iz vzorca).

Iz programov `grafi.r` in `analiza.r` odstrani tudi oba ukaza `source` - program `konzola.r` namreč kličeš že prej, potem pa še enkrat pokličeš `grafi.r`, zaradi česar program zaide v neskončno zanko. Skratka, program mora delovati, če poženeš `projekt.r`.

Svetoval bi še, da v poročilu še malo opišeš, kaj natančno lahko prebereš iz grafa - kje prodaja največ raste, kje pada, pa mogoče še kakšno interpretacijo, zakaj je tako.

**Comment by SanjaAudi** [comment]
Sem popravila, ampak nisem brisala source za konzolo ker mi ni jasno iz kje bo potem pobral podatke ko potrebuje tabelo? Hvala

**Comment by jaanos** [comment]
Če vključiš `konzola.r` vsakič znova, načeloma ni narobe - samo po nepotrebnem vsakič znova uvažaš podatke. Kakorkoli, zdaj se program zažene, tako da sem dodal povezavo na repozitorij za zagovore.

Če se še nisi, se s profesorjem dogovori za termin zagovora. Če boš še kaj spreminjala, mi javi, da posodobim povezavo.

**Comment by SanjaAudi** [comment]
Če izbrišem ta source bo vseeno vedel iz kje naj vzame podatke - tabele ? Hvala

**Comment by jaanos** [comment]
Če poženeš `projekt.r`, ta najprej pokliče `uvoz.r`, ta pa pokliče `konzola.r`, ki uvozi podatke. Ti so potem dostopni v nadaljevanju programa.

**Comment by SanjaAudi** [comment]
Super, sem uredila še to da program ne zapravlja časa vsakič zaradi tega. Tako da sedaj sem čisto konec, upam :) Hvala

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo. Lahko zapreš tale issue.
